// export const GET_COUNTRIES = "GET_COUNTRIES";
// export const GET_COUNTRY = "GET_COUNTRY";
// export const ORDER_COUNTRIES = "ORDER_COUNTRIES";
// export const GET_COUNTRY_NAME = "SEARCH_COUNTRIES";


// export const ORDER_POPULATION = "FILTER_CONTINENT";
// export const FILTER_CONTINENT = "FILTER_CONTINENT";



// export const POST_ACTIVITIES= "ORDER_COUNTRIES";
// export const GET_ACTIVITY = "GET_ACTIVITY";
// export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
// export const FILTER_ACTIVITY = "FILTER_ACTIVITY";